### ISSUE TITLE
Inconsistency in file name when generating data utility files for parametric paths

### ISSUE THREAD

**Issue by meronig** [DITAS-Project/SDK-Blueprint#4]
When generating data utility files, the convention 

> path-{parameter}

is used for parametric paths /path/{parameter}. 
However, when assembling the blueprints, files are expected to follow the convention 

> path{parameter}

To reproduce, create a swagger file with the following methods:

> /nutritional-data/{filter}
> /blood-test/component/{component}/average/{startAgeRange}-{endAgeRange}

**Comment by slayo11** [comment]
@meronig, could you please attach the swagger file? It would really speed up the reproduction of the error
Thank you

**Comment by meronig** [comment]
[Here](https://github.com/DITAS-Project/SDK-Blueprint/files/3746866/scenario13.zip) you go. Enclosed in this archive you can also find the expected abstract blueprint.

**Comment by slayo11** [comment]
Fixed with the last merge, let's wait for the double check of tomorrow's meeting to close it.

**Comment by slayo11** [comment]
Fixed
