### ISSUE TITLE
Blueprint generation from data utility files not working

### ISSUE THREAD

**Issue by meronig** [DITAS-Project/SDK-Blueprint#5]
When generating the blueprint from data utility files, function add_data_management fails.

> Traceback (most recent call last):
>   File "main.py", line 233, in <module>
>     args.func(args)
>   File "main.py", line 91, in handler_create
>     generate_blueprint(vdc_repo, vdc_repo_path, dal_repo_paths, False, args.push)
>   File "main.py", line 35, in generate_blueprint
>     blueprint.add_data_management()
>   File "C:\Users\giovanni.meroni\Documents\Visual Studio 2015\Projects\DITAS\BPGen\blueprint\blueprint.py", line 251, in add_data_management
>     dm_metric_elem[DM_EL_ATT_DU_PR_SE_ID] = metric[METRIC_NAME]
> KeyError: 'name'

To reproduce, follow the standard workflow.

**Comment by slayo11** [comment]
As mentioned, there is a mismatch between DITAS_D3.3 schema definition for DataUtility, Security, Privacy JSON objects and provided specifications during meetings.
Solving this issue will need further details.

**Comment by slayo11** [comment]
From DITAS_D3.3: "With respect to the contents described in D3.2 Section 3.2, the data structure was slightly changed. **In particular, properties associated to a metric are no longer defined as JSON objects. Instead, they are defined as JSON properties.** Changes in the JSON schema are highlighted in bold."

Taking from 'scenario13' and what I understand from the specification, the following is wrong
```
          {
            "id": "accuracy_08",
            "description": "Accuracy",
            "type": "Accuracy",
            "properties": {
              "accuracy": {
                "minimum": 80,
                "unit": "percentage"
              }
            }
```
"properties" value should not be a JSON object but additional properties

**Comment by slayo11** [comment]
Fixed after last merge: 'DITAS-Project/new-data-management-template'.
