### ISSUE TITLE
Data utility files do not follow blueprint structure

### ISSUE THREAD

**Issue by meronig** [DITAS-Project/SDK-Blueprint#6]
When generating data utility files from a swagger document, the structure of those files do not reflect the one adopted by blueprints.

The reference structure to be used for those files is the one specified in the DATA_MANAGEMENT section of the UC blueprints, e.g., [here](https://github.com/DITAS-Project/osr-use-case/blob/master/scenario13/abstract-blueprint-scenario-13.json)

**Comment by slayo11** [comment]
Fixed after last merge: 'DITAS-Project/new-data-management-template'.
